server:
  host: 0.0.0.0   # 服务器地址
  port: 5000        # 端口

nickname: Ruibin_Ningh   # 昵称
avatar: avatar.png        # 头像文件名

api_key: your-api-key-here   # API Key
view_time_limit_days: 7      # 可见天数
comment: false               # 是否开启评论
